module.exports = {
	//获取验证码
	'/user/getCaptcha':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/user/getCaptcha':'/user/getCaptcha'
		}
	},
	//检查验证码
	'/user/checkCaptcha':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/user/checkCaptcha':'/user/checkCaptcha'
		}
	},
	//登录接口
	'/user/login':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/user/login':'/user/login'
		}
	},
	//注册接口
	'/user/register':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/user/register':'/user/register'
		}
	},
	//检查当前用户名是否可用
	'/user/checkUserName':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/user/checkUserName':'/user/checkUserName'
		}
	},
	//是否已经登陆
	'/user/islogin':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/user/islogin':'/user/islogin'
		}
	},
	//获取所有用户信息
	'/manage/getUser':{
		target:'http://127.0.0.1:12345/',
		changeOrigin:true,
		pathRewrite:{
			'^/manage/getUser':'/manage/getUser'
		}
	},
}